Repository Neplex/ArchiTXT, pull requests merged in 2025-04, with the labels that each got.

#57 :loud_sound: Log clustering data when debug is enable
  architxt/similarity.py
  architxt/simplification/tree_rewriting/__init__.py
  pyproject.toml
Labels: enhancement

#58 :bug: Fix tree reduction logic to prevent flat tree generation
  architxt/nlp/parser/__init__.py
  architxt/similarity.py
  architxt/simplification/tree_rewriting/operations/reductions.py
  architxt/tree.py
  docs/examples/corpus_exploration.ipynb
Labels: bug

#59 :memo: Add database integration example
  architxt/schema.py
  architxt/similarity.py
  docs/examples.rst
  docs/examples/corpus_exploration.ipynb
  docs/examples/database_integration.ipynb
  pyproject.toml
Labels: documentation

#63 :sparkles: Add document database loader
  architxt/cli/loader.py
  architxt/database/__init__.py
  architxt/database/documents.py
  architxt/database/sql.py
  pyproject.toml
  tests/database/test_read_documents.py
Labels: enhancement

#62 :sparkles: Add the export to a graph database
  architxt/cli/__init__.py
  architxt/cli/export.py
  architxt/cli/loader.py
  architxt/database/__init__.py
  architxt/database/export/__init__.py
  architxt/database/export/graph.py
  architxt/database/loader/__init__.py
  architxt/database/loader/documents.py
  architxt/database/loader/sql.py
  docker-compose.yml
  docs/examples/database_integration.ipynb
  pyproject.toml
  tests/database/test_read_database.py
  tests/database/test_read_documents.py
Labels: enhancement

#67 :recycle: Refactor Tree class
  architxt/cli/__init__.py
  architxt/cli/export.py
  architxt/database/export/graph.py
  architxt/database/loader/documents.py
  architxt/database/loader/sql.py
  architxt/generator/__init__.py
  architxt/metrics.py
  architxt/nlp/parser/__init__.py
  architxt/nlp/parser/benepar.py
  architxt/nlp/parser/corenlp.py
  architxt/schema.py
  architxt/similarity.py
  architxt/simplification/simple_rewrite.py
  architxt/simplification/tree_rewriting/__init__.py
  architxt/simplification/tree_rewriting/operations/collections.py
  architxt/simplification/tree_rewriting/operations/groups.py
  architxt/simplification/tree_rewriting/operations/reductions.py
  architxt/simplification/tree_rewriting/operations/relations.py
  architxt/simplification/tree_rewriting/utils.py
  architxt/tree.py
  docs/examples/corpus_exploration.ipynb
  docs/examples/database_integration.ipynb
  tests/database/test_read_database.py
  tests/database/test_read_documents.py
  tests/simplification/tree_rewriting/operations/test_find_collections.py
  tests/simplification/tree_rewriting/operations/test_find_relations.py
  tests/simplification/tree_rewriting/operations/test_find_subgroups.py
  tests/simplification/tree_rewriting/operations/test_merge_groups.py
  tests/simplification/tree_rewriting/operations/test_operations.py
  tests/test_schema.py
  tests/test_strategies.py
Labels: enhancement, python

#69 :technologist: Uniformize the CLI
  architxt/cli/__init__.py
  architxt/cli/loader.py
  architxt/database/export/graph.py
  architxt/ui/__init__.py
Labels: enhancement

#70 :recycle: Moved sampling logic into document loader
  architxt/cli/loader.py
  architxt/database/loader/documents.py
Labels: python
